#!/usr/bin/env bash
# Auto-generated by generate-s3-manifest.js
# Uploads institution images to s3://art-explore-db-images/institutions/
# Run:  bash s3-upload.sh

set -euo pipefail

BUCKET="art-explore-db-images"
PREFIX="institutions"

# ── art-house-foundation (2 files) ──
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/art-house-foundation/image-1.jpg" "s3://art-explore-db-images/institutions/art-house-foundation/image-1.jpg" --content-type "image/jpeg" --profile artexplore-dev
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/art-house-foundation/image-2.png" "s3://art-explore-db-images/institutions/art-house-foundation/image-2.png" --content-type "image/png" --profile artexplore-dev

# ── arthouse-contemporary (2 files) ──
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/arthouse-contemporary/image-1.jpg" "s3://art-explore-db-images/institutions/arthouse-contemporary/image-1.jpg" --content-type "image/jpeg" --profile artexplore-dev
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/arthouse-contemporary/image-2.png" "s3://art-explore-db-images/institutions/arthouse-contemporary/image-2.png" --content-type "image/png" --profile artexplore-dev

# ── ko-art-space (1 file) ──
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/ko-art-space/image-1.webp" "s3://art-explore-db-images/institutions/ko-art-space/image-1.webp" --content-type "image/webp" --profile artexplore-dev

# ── omenka-gallery (1 file) ──
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/omenka-gallery/image-1.webp" "s3://art-explore-db-images/institutions/omenka-gallery/image-1.webp" --content-type "image/webp" --profile artexplore-dev

# ── quintessence-gallery (2 files) ──
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/quintessence-gallery/image-1.jpg" "s3://art-explore-db-images/institutions/quintessence-gallery/image-1.jpg" --content-type "image/jpeg" --profile artexplore-dev
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/quintessence-gallery/image-2.webp" "s3://art-explore-db-images/institutions/quintessence-gallery/image-2.webp" --content-type "image/webp" --profile artexplore-dev

# ── smo-contemporary-art (1 file) ──
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/smo-contemporary-art/image-1.jpg" "s3://art-explore-db-images/institutions/smo-contemporary-art/image-1.jpg" --content-type "image/jpeg" --profile artexplore-dev

# ── tiwani-contemporary (1 file) ──
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/tiwani-contemporary/image-1.webp" "s3://art-explore-db-images/institutions/tiwani-contemporary/image-1.webp" --content-type "image/webp" --profile artexplore-dev

# ── yemisi-shyllon-museum-of-art (1 file) ──
aws s3 cp "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions/yemisi-shyllon-museum-of-art/image-1.png" "s3://art-explore-db-images/institutions/yemisi-shyllon-museum-of-art/image-1.png" --content-type "image/png" --profile artexplore-dev


# ── OR: sync the entire folder in one shot ──
# aws s3 sync "/Users/tobilesi/Projects/art-explore-web/public/uploads/institutions" "s3://art-explore-db-images/institutions"
echo "✅  Done — 11 files uploaded to s3://art-explore-db-images/institutions/"